import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import Image from 'next/image';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Assuming the logo is rendered within the children, you might need to adjust this
            based on where the Image component with src="/images/logo-512x512.png" is actually used.
            If it's directly in this layout, uncomment and place it here. */}
        {/* <Image src="/images/logo-512x512.png" alt="Logo" width={512} height={512} priority /> */}

        {/* Render the rest of the page content */}
        {children}
      </body>
    </html>
  );
}
