export const images = {
    angelPremium: require('@/assets/images/angelPremium.png'),
    angry_female: require('@/assets/images/angry female.png'),
    angry_male: require('@/assets/images/angry male.png'),
    angryPremium: require('@/assets/images/angryPremium.png'),
    anxious_female: require('@/assets/images/anxious female.png'),
    anxious_male: require('@/assets/images/anxious male.png'),
    ashamed_female: require('@/assets/images/ashamed female.png'),
    ashamed_male: require('@/assets/images/ashamed male.png'),
    blog1: require('@/assets/images/blog1.png'),
    blog2: require('@/assets/images/blog2.png'),
    blog3: require('@/assets/images/blog3.png'),
    blog4: require('@/assets/images/blog4.png'),
    blog5: require('@/assets/images/blog5.png'),
    blushPremium: require('@/assets/images/blushPremium.png'),
    cloudPremium: require('@/assets/images/cloudPremium.png'),
    confused_female: require('@/assets/images/confused female.png'),
    confused_male: require('@/assets/images/confused male.png'),
    devilPremium: require('@/assets/images/devilPremium.png'),
    happy_female: require('@/assets/images/happy female.png'),
    happy_male: require('@/assets/images/happy male.png'),
    img3274: require('@/assets/images/IMG_3274.png'),
    img3275: require('@/assets/images/IMG_3275.png'),
    img3276: require('@/assets/images/IMG_3276.png'),
    img3278: require('@/assets/images/IMG_3278.png'),
    img3279: require('@/assets/images/IMG_3279.png'),
    img3354: require('@/assets/images/IMG_3354.png'),
    img3355: require('@/assets/images/IMG_3355.png'),
    img3356: require('@/assets/images/IMG_3356.png'),
    img3357: require('@/assets/images/IMG_3357.png'),
    img3358: require('@/assets/images/IMG_3358.png'),
    img3359: require('@/assets/images/IMG_3359.png'),
    img3360: require('@/assets/images/IMG_3360.png'),
    img3361: require('@/assets/images/IMG_3361.png'),
    img3362: require('@/assets/images/IMG_3362.png'),
    img3363: require('@/assets/images/IMG_3363.png'),
    img3364: require('@/assets/images/IMG_3364.png'),
    img3365: require('@/assets/images/IMG_3365.png'),
    img3366: require('@/assets/images/IMG_3366.png'),
    img3367: require('@/assets/images/IMG_3367.png'),
    img3368: require('@/assets/images/IMG_3368.png'),
    img3369: require('@/assets/images/IMG_3369.png'),    
    logo192: require('@/assets/images/logo-192x192.png'),
    logo512: require('@/assets/images/logo-512x512.png'),
    logo1024:  require('@/assets/images/LOGO1024x1024.png'),
    logo1242:  require('@/assets/images/LOGO1242x2436.png'),
    marija:  require('@/assets/images/Marija.jpg'),
    sad_female: require('@/assets/images/sad female.png'),
    sad_male: require('@/assets/images/sad male.png'),
    scared_female: require('@/assets/images/scared female.png'),
    scared_male: require('@/assets/images/scared male.png'),
    tired_female: require('@/assets/images/tired female.png'),
    tired_male: require('@/assets/images/tired male.png'),
    unmotivated_female: require('@/assets/images/unmotivated female.png'),
    unmotivated_male: require('@/assets/images/unmotivated male.png'),
  };